title: DTRG Docs
description: Documentation Wiki for the DTRG group at the University of Auckland
theme: just-the-docs

url: https://UoA-DTRG.github.io

aux_links:
  DTRG Website: https://dtrg.org

exclude:
  - Tools/
  - .vscode/
  - .github/
  - .gitignore
  - .gitattributes
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - yarn.lock
  - package.json
  - package-lock.json
  - .DS_Store
  - .ruby-version
  - .ruby-gemset
  - .jekyll-cache/
  - .jekyll-metadata
  - .sass-cache/
  - .bundle/
  - vendor/
  - .idea/
  